name: 'Copilot Usage Report'
description: 'Export Copilot usage for an Organization to CSV or JSON'
branding:
  icon: 'download'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  org_name: 
    description: 'Organization name'
    required: true
  file_path:
    description: 'CSV or JSON File path'
    required: true
runs:
  using: 'node20'
  main: 'app/index.js'
